{
 "title": "Devtool / Admin / Workspace",
 "tags": [ "devtool-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total, cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_labels{cluster=~\"$cluster\", nodepool=\"workspace-pool\"}, node)"
    }
   },
   {
    "name": "workspace",
    "query": {
     "query": "label_values(kube_pod_labels{cluster=~\"$cluster\",component=\"workspace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Workspace info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Workspace Owner",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_labels{pod=\"$workspace\", owner=~\".+\"}",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Workspace ID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_labels{pod=\"$workspace\", metaID=~\".+\"}",
     "legendFormat": "{{metaID}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - kube_pod_created{pod=\"$workspace\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\", cluster=\"$cluster\", pod=\"$workspace\"}[$__rate_interval])\n) by (pod)\n",
     "legendFormat": "CPU Utilization"
    }
   ]
  },
  {
   "title": "CPU Saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\", cluster=\"$cluster\", pod=\"$workspace\"}[$__rate_interval])\n) by (pod)\n/\nsum(\n  kube_pod_container_resource_limits{container!=\"POD\", cluster=\"$cluster\", pod=\"$workspace\", resource=\"cpu\"}\n ) by (pod)\n",
     "legendFormat": "CPU Saturation"
    },
    {
     "expr": "sum(\n  rate(container_cpu_cfs_throttled_seconds_total{container!=\"POD\", pod!=\"\", cluster=\"$cluster\", pod=\"$workspace\"}[$__rate_interval])\n) by (pod)\n",
     "legendFormat": "CPU Throttles"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{container!=\"POD\", container!=\"\", cluster=\"$cluster\", pod=\"$workspace\"}\n) by (pod)\n",
     "legendFormat": "Memory Utilization"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{container!=\"POD\", container!=\"\", cluster=\"$cluster\", pod=\"$workspace\"}\n) by (pod)\n/\nsum(\n  kube_pod_container_resource_limits{container!=\"POD\", cluster=\"$cluster\", pod=\"$workspace\", resource=\"memory\"}\n) by (pod)\n",
     "legendFormat": "Memory Saturation"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(container_network_receive_bytes_total{container!=\"POD\", pod!=\"\", cluster=\"$cluster\", pod=\"$workspace\"}[$__rate_interval])\n) by (pod)\n",
     "legendFormat": "Received"
    },
    {
     "expr": "sum (\n  rate(container_network_transmit_bytes_total{container!=\"POD\", pod!=\"\", cluster=\"$cluster\", pod=\"$workspace\"}[$__rate_interval])\n) by (pod)\n",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Network Saturation (Packets dropped)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(container_network_receive_packets_dropped_total{container!=\"POD\", pod!=\"\", cluster=\"$cluster\", pod=\"$workspace\"}[$__rate_interval])\n) by (pod)\n",
     "legendFormat": "While Receiving"
    },
    {
     "expr": "sum (\n  rate(container_network_transmit_packets_dropped_total{container!=\"POD\", pod!=\"\", cluster=\"$cluster\", pod=\"$workspace\"}[$__rate_interval])\n) by (pod)\n",
     "legendFormat": "While Transmitting"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "errors/s" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(container_network_receive_errors_total{container!=\"POD\", pod!=\"\", cluster=\"$cluster\", pod=\"$workspace\"}[$__rate_interval])\n) by (pod)\n",
     "legendFormat": "While Receiving"
    },
    {
     "expr": "sum (\n  rate(container_network_transmit_errors_total{container!=\"POD\", pod!=\"\", cluster=\"$cluster\", pod=\"$workspace\"}[$__rate_interval])\n) by (pod)\n",
     "legendFormat": "While Transmitting"
    }
   ]
  }
 ]
}