{
 "title": "Devtool / Admin / Node",
 "tags": [ "devtool-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total, cluster)"
    }
   },
   {
    "name": "nodepool",
    "query": {
     "query": "label_values(kube_node_labels{cluster=\"$cluster\"}, nodepool)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_labels{cluster=~\"$cluster\", nodepool=\"$nodepool\"}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kernel",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_uname_info{node=\"$node\"}",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"$node\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "# of Workspaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(\n  sum(container_cpu_cfs_periods_total{node=\"$node\", container=\"workspace\"} * on(pod) group_left(workspace_type) kube_pod_labels{component=\"workspace\"}) by (pod, workspace_type)\n) by (workspace_type)\n",
     "legendFormat": "{{workspace_type}}"
    }
   ]
  },
  {
   "title": "Top CPU Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    rate(container_cpu_usage_seconds_total{container!=\"\", node=\"$node\"}[$__rate_interval])\n  ) by (pod)\n)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top Memory Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    container_memory_working_set_bytes{container!=\"\", node=\"$node\"}\n  ) by (pod)\n)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top Network Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,\n  sum (\n    rate(container_network_receive_bytes_total{pod!=\"\", cluster=\"$cluster\", node=\"$node\"}[$__rate_interval])\n  ) by (pod) +\n  sum (\n    rate(container_network_transmit_bytes_total{pod!=\"\", node=\"$node\"}[$__rate_interval])\n  ) by (pod)\n)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current Top 10 CPU consumers",
   "type": "table-old",
   "description": "Top 10 CPU consumer pods of the selected Node\n\nIf you'd like to see more details about resource consumption of a particular pod, you can do so by clicking at the pod name.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sort(\n  topk(10,\n    sum(\n      rate(container_cpu_usage_seconds_total{container!=\"\", node=\"$node\"}[$__rate_interval])\n    ) by (pod)\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Current Top 10 Memory consumers",
   "type": "table-old",
   "description": "Top 10 Memory consumer pods of the selected Node\n\nIf you'd like to see more details about resource consumption of a particular pod, you can do so by clicking at the pod name.\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "sort(\n  topk(10,\n    sum(\n      container_memory_working_set_bytes{container!=\"\", node=\"$node\"}\n    ) by (pod)\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Current Top 10 Network consumers",
   "type": "table-old",
   "description": "Top 10 Network consumer pods of the selected Node\n\nIf you'd like to see more details about resource consumption of a particular pod, you can do so by clicking at the pod name.\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "sort(\n  topk(10,\n    sum (\n      rate(container_network_receive_bytes_total{pod!=\"\", cluster=\"$cluster\", node=\"$node\"}[$__rate_interval])\n    ) by (pod) +\n    sum (\n      rate(container_network_transmit_bytes_total{pod!=\"\", node=\"$node\"}[$__rate_interval])\n    ) by (pod)\n  )\n)\n"
    }
   ]
  },
  {
   "title": "USE Method",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  (1 - rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"})\n)\n",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$node\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{instance=\"$node\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{instance=\"$node\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{instance=\"$node\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\"} - node_memory_MemAvailable_bytes{instance=\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\"}",
     "legendFormat": "Memory Size"
    }
   ]
  },
  {
   "title": "Memory Saturation (page faults)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_vmstat_pgmajfault:rate1m{instance=\"$node\"}",
     "legendFormat": "Memory Saturation"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "instance:node_network_receive_bytes_excluding_lo:rate1m{instance=\"$node\"}",
     "legendFormat": "Received"
    },
    {
     "expr": "instance:node_network_transmit_bytes_excluding_lo:rate1m{instance=\"$node\"}",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Network Saturation (drops)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "instance:node_network_receive_drop_excluding_lo:rate1m{instance=\"$node\"}",
     "legendFormat": "Received"
    },
    {
     "expr": "instance:node_network_transmit_drop_excluding_lo:rate1m{instance=\"$node\"}",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance_device:node_disk_io_time_seconds:rate1m{instance=\"$node\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance_device:node_disk_io_time_weighted_seconds:rate1m{instance=\"$node\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 -\n(\n  max without (mountpoint, fstype) (node_filesystem_avail_bytes{fstype!=\"shiftfs\", instance=\"$node\"})\n/\n  max without (mountpoint, fstype) (node_filesystem_size_bytes{fstype!=\"shiftfs\", instance=\"$node\"})\n)\n",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}