{
 "title": "Devtool / SLOs / Login",
 "tags": [ "devtool-mixin" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "auth_host",
    "query": {
     "query": "label_values(devtool_server_login_requests_total{auth_host=~\"gitlab.com|github.com|bitbucket.org\"}, auth_host)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(devtool_server_login_requests_total{auth_host=~\"gitlab.com|github.com|bitbucket.org\"}, cluster)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "SLO and Error budget",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "0.95", "legendFormat": "Availability target" },
    {
     "expr": "(1 - (\n  sum(rate(devtool_server_login_requests_total{status=\"failed\"}[30d]))\n  /\n  sum(rate(devtool_server_login_requests_total[30d]))\n)) - 0.95",
     "legendFormat": "Monthly error budget remaining"
    }
   ]
  },
  { "title": "Burn ratios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Login failure ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\"}[5m]))\n/\nsum(rate(devtool_server_login_requests_total[5m]))",
     "legendFormat": "5m failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\"}[30m]))\n/\nsum(rate(devtool_server_login_requests_total[30m]))",
     "legendFormat": "30m failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\"}[1h]))\n/\nsum(rate(devtool_server_login_requests_total[1h]))",
     "legendFormat": "1h failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\"}[2h]))\n/\nsum(rate(devtool_server_login_requests_total[2h]))",
     "legendFormat": "2h failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\"}[6h]))\n/\nsum(rate(devtool_server_login_requests_total[6h]))",
     "legendFormat": "6h failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\"}[1d]))\n/\nsum(rate(devtool_server_login_requests_total[1d]))",
     "legendFormat": "1d failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\"}[3d]))\n/\nsum(rate(devtool_server_login_requests_total[3d]))",
     "legendFormat": "3d failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\"}[30d]))\n/\nsum(rate(devtool_server_login_requests_total[30d]))",
     "legendFormat": "30d failure ratio"
    },
    { "expr": "0.05", "legendFormat": "Failure ratio threshold" }
   ]
  },
  {
   "title": "$cluster: Login failure ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\", cluster=~\"$cluster\"}[5m]))\n/\nsum(rate(devtool_server_login_requests_total{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "5m failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\", cluster=~\"$cluster\"}[30m]))\n/\nsum(rate(devtool_server_login_requests_total{cluster=~\"$cluster\"}[30m]))",
     "legendFormat": "30m failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\", cluster=~\"$cluster\"}[1h]))\n/\nsum(rate(devtool_server_login_requests_total{cluster=~\"$cluster\"}[1h]))",
     "legendFormat": "1h failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\", cluster=~\"$cluster\"}[2h]))\n/\nsum(rate(devtool_server_login_requests_total{cluster=~\"$cluster\"}[2h]))",
     "legendFormat": "2h failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\", cluster=~\"$cluster\"}[6h]))\n/\nsum(rate(devtool_server_login_requests_total{cluster=~\"$cluster\"}[6h]))",
     "legendFormat": "6h failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\", cluster=~\"$cluster\"}[1d]))\n/\nsum(rate(devtool_server_login_requests_total{cluster=~\"$cluster\"}[1d]))",
     "legendFormat": "1d failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\", cluster=~\"$cluster\"}[3d]))\n/\nsum(rate(devtool_server_login_requests_total{cluster=~\"$cluster\"}[3d]))",
     "legendFormat": "3d failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\", cluster=~\"$cluster\"}[30d]))\n/\nsum(rate(devtool_server_login_requests_total{cluster=~\"$cluster\"}[30d]))",
     "legendFormat": "30d failure ratio"
    },
    { "expr": "0.05", "legendFormat": "Failure ratio threshold" }
   ]
  },
  {
   "title": "$auth_host: Login failure ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "repeat": "auth_host",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\", auth_host=~\"$auth_host\"}[5m]))\n/\nsum(rate(devtool_server_login_requests_total{auth_host=~\"$auth_host\"}[5m]))",
     "legendFormat": "5m failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\", auth_host=~\"$auth_host\"}[30m]))\n/\nsum(rate(devtool_server_login_requests_total{auth_host=~\"$auth_host\"}[30m]))",
     "legendFormat": "30m failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\", auth_host=~\"$auth_host\"}[1h]))\n/\nsum(rate(devtool_server_login_requests_total{auth_host=~\"$auth_host\"}[1h]))",
     "legendFormat": "1h failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\", auth_host=~\"$auth_host\"}[2h]))\n/\nsum(rate(devtool_server_login_requests_total{auth_host=~\"$auth_host\"}[2h]))",
     "legendFormat": "2h failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\", auth_host=~\"$auth_host\"}[6h]))\n/\nsum(rate(devtool_server_login_requests_total{auth_host=~\"$auth_host\"}[6h]))",
     "legendFormat": "6h failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\", auth_host=~\"$auth_host\"}[1d]))\n/\nsum(rate(devtool_server_login_requests_total{auth_host=~\"$auth_host\"}[1d]))",
     "legendFormat": "1d failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\", auth_host=~\"$auth_host\"}[3d]))\n/\nsum(rate(devtool_server_login_requests_total{auth_host=~\"$auth_host\"}[3d]))",
     "legendFormat": "3d failure ratio"
    },
    {
     "expr": "sum(rate(devtool_server_login_requests_total{status=\"failed\", auth_host=~\"$auth_host\"}[30d]))\n/\nsum(rate(devtool_server_login_requests_total{auth_host=~\"$auth_host\"}[30d]))",
     "legendFormat": "30d failure ratio"
    },
    { "expr": "0.05", "legendFormat": "Failure ratio threshold" }
   ]
  },
  {
   "title": "Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Login rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(devtool_server_login_requests_total[5m]))",
       "legendFormat": "5m login rate"
      }
     ]
    },
    {
     "title": "$cluster: Login rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
     "repeat": "cluster",
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(devtool_server_login_requests_total{cluster=~\"$cluster\"}[5m]))",
       "legendFormat": "5m login rate"
      }
     ]
    },
    {
     "title": "$cluster: Login rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(devtool_server_login_requests_total{cluster=~\"$cluster\"}[5m]))",
       "legendFormat": "5m login rate"
      }
     ]
    },
    {
     "title": "$auth_host: Login rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
     "repeat": "auth_host",
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(devtool_server_login_requests_total{auth_host=~\"$auth_host\"}[5m]))",
       "legendFormat": "5m login rate"
      }
     ]
    },
    {
     "title": "$auth_host: Login rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(devtool_server_login_requests_total{auth_host=~\"$auth_host\"}[5m]))",
       "legendFormat": "5m login rate"
      }
     ]
    },
    {
     "title": "$auth_host: Login rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(devtool_server_login_requests_total{auth_host=~\"$auth_host\"}[5m]))",
       "legendFormat": "5m login rate"
      }
     ]
    }
   ]
  }
 ]
}