{
 "title": "Devtool / Component / server",
 "tags": [ "devtool-mixin" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"server\"}, cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=~\"$cluster\", pod=~\"server.*\"}, node)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=~\"$cluster\", node=~\"$node\", pod=~\"server.*\"}, pod)"
    }
   },
   {
    "name": "method",
    "label": "API Method",
    "query": {
     "query": "label_values(devtool_server_api_calls_total{cluster=~\"$cluster\"}, method)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "http_route",
    "label": "HTTP Route",
    "query": {
     "query": "label_values(devtool_server_http_requests_total, route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (devtool_version_info{}) by (cluster, devtool_version)",
       "legendFormat": "{{ cluster }}: {{ devtool_version }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Websocket API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API Request Rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(devtool_server_api_calls_total{cluster=~\"$cluster\", pod=~\"$pod\", method=~\"$method\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API request duration 50th",
   "type": "timeseries",
   "description": "A histogram quantile of the API requests grouped by methods and bucket (duration) size.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum (rate(devtool_server_api_calls_duration_seconds_bucket{cluster=~\"$cluster\", pod=~\"$pod\", method=~\"$method\"}[5m])) by (method, le))",
     "legendFormat": "50% {{method}} {{le}}"
    }
   ]
  },
  {
   "title": "Server Errors [5m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(devtool_server_api_calls_total{cluster=~\"$cluster\", pod=~\"$pod\", method=~\"$method\", statusCode!~\"2.*|3.*|4.*\"}[5m])\n) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API request duration 95th",
   "type": "timeseries",
   "description": "A histogram quantile of the API requests grouped by methods and bucket (duration) size.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(devtool_server_api_calls_duration_seconds_bucket{cluster=~\"$cluster\", pod=~\"$pod\", method=~\"$method\"}[5m])) by (method, le))",
     "legendFormat": "95% {{method}} {{le}}"
    }
   ]
  },
  {
   "title": "User Errors [5m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(devtool_server_api_calls_total{cluster=~\"$cluster\", pod=~\"$pod\", method=~\"$method\", statusCode=~\"4.*\"}[5m])\n) by (method, statusCode)",
     "legendFormat": "{{method}} code: {{statusCode}}"
    }
   ]
  },
  {
   "title": "API Saturation (Rate Limited requests)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(devtool_server_api_calls_total{cluster=~\"$cluster\", pod=~\"$pod\", method=~\"$method\", statusCode=\"429\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Websocket Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Websocket connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(server_websocket_connection_count{cluster=~\"$cluster\"}) by (cluster)",
       "legendFormat": "{{cluster}} {{pod}}"
      }
     ]
    },
    {
     "title": "Websocket Clients",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(server_websocket_connection_count{cluster=~\"$cluster\", pod=~\"$pod\"}) by (cluster, clientType)",
       "legendFormat": "{{cluster}} {{clientType}}"
      }
     ]
    },
    {
     "title": "Server API connections rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(rate(devtool_server_api_connections_total{cluster=~\"$cluster\", pod=~\"$pod\"}[5m])) by (cluster)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Server API connections closed rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "sum(rate(devtool_server_api_connections_closed_total{cluster=~\"$cluster\"}[5m])) by (cluster)",
       "legendFormat": "{{cluster}} {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$http_route: HTTP Request rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(devtool_server_http_requests_total{cluster=~\"$cluster\", statusCode=~\"2..\", route=~\"$http_route\"}[5m])) by (cluster)",
       "legendFormat": "{{cluster}} - 2xx"
      },
      {
       "expr": "sum(rate(devtool_server_http_requests_total{cluster=~\"$cluster\", statusCode=~\"3..\", route=~\"$http_route\"}[5m])) by (cluster)",
       "legendFormat": "{{cluster}} - 3xx"
      },
      {
       "expr": "sum(rate(devtool_server_http_requests_total{cluster=~\"$cluster\", statusCode=~\"4..\", route=~\"$http_route\"}[5m])) by (cluster)",
       "legendFormat": "{{cluster}} - 4xx"
      },
      {
       "expr": "sum(rate(devtool_server_http_requests_total{cluster=~\"$cluster\", statusCode=~\"5..\", route=~\"$http_route\"}[5m])) by (cluster)",
       "legendFormat": "{{cluster}} - 5xx"
      }
     ]
    },
    {
     "title": "$http_route: HTTP Request duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(rate(devtool_server_http_request_duration_seconds_bucket{cluster=~\"$cluster\", route=~\"$http_route\"}[5m])) by (cluster, le)\n )",
       "legendFormat": "{{cluster}} - 99th percentile"
      },
      {
       "expr": "histogram_quantile(0.95, \n  sum(rate(devtool_server_http_request_duration_seconds_bucket{cluster=~\"$cluster\", route=~\"$http_route\"}[5m])) by (cluster, le)\n )",
       "legendFormat": "{{cluster}} - 95th percentile"
      },
      {
       "expr": "histogram_quantile(0.50, \n  sum(rate(devtool_server_http_request_duration_seconds_bucket{cluster=~\"$cluster\", route=~\"$http_route\"}[5m])) by (cluster, le)\n )",
       "legendFormat": "{{cluster}} - 50th percentile"
      },
      {
       "expr": "sum(rate(devtool_server_http_request_duration_seconds_sum{cluster=~\"$cluster\", route=~\"$http_route\"}[5m])) by (cluster)\n/\nsum(rate(devtool_server_http_request_duration_seconds_count{cluster=~\"$cluster\", route=~\"$http_route\"}[5m])) by (cluster)",
       "legendFormat": "{{cluster}} - avg"
      }
     ]
    }
   ]
  },
  { "title": "Messaging / Broadcasting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Redis updates received [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(devtool_redis_updates_received_total{cluster=~\"$cluster\", pod=~\"$pod\"}[1m])) by (channel)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis updates completed with outcome [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(devtool_redis_updates_completed_total{cluster=~\"$cluster\", pod=~\"$pod\"}[1m])) by (channel, error)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients subscribed to updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(devtool_server_subscribers_registered{cluster=~\"$cluster\", pod=~\"$pod\"}) by (type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node.js Runtime Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage (as seen by the runtime process)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{cluster=~\"$cluster\", pod=~\"$pod\", job=\"server\"}",
       "legendFormat": "{{cluster}} - {{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage (as seen by the runtime process)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{cluster=~\"$cluster\", job=\"server\"}[1m])",
       "legendFormat": "{{cluster}} - {{kubernetes_pod_node_name}} - {{ kubernetes_pod_name }}"
      }
     ]
    },
    {
     "title": "Node.js: Event loop lag (s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "nodejs_eventloop_lag_seconds{cluster=~\"$cluster\", job=\"server\", pod=~\"$pod\"}",
       "legendFormat": "{{cluster}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Node.js: File Handles",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "nodejs_active_handles_total{cluster=~\"$cluster\", job=\"server\", pod=~\"$pod\"}",
       "legendFormat": "{{cluster}} - {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}