{
 "title": "Registry facade download bytes",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"registry-facade\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Downloads per source",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(blobSource) (devtool_registry_facade_registry_blob_req_dl_total{cluster=~\"$cluster\"})",
     "legendFormat": "{{blobSource}}"
    }
   ]
  },
  {
   "title": "Download speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(blobSource) (rate(devtool_registry_facade_registry_blob_req_bytes_second_sum{cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download size per source",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(devtool_registry_facade_registry_blob_req_bytes_total{cluster=~\"$cluster\"}[24h])) by(blobSource)",
     "legendFormat": "{{blobSource}}"
    }
   ]
  },
  {
   "title": "Proxy",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 18, "x": 5, "y": 10 },
   "targets": [
    {
     "expr": "sum(\n    rate(devtool_registry_facade_registry_blob_req_bytes_second_bucket{cluster=~\"$cluster\", blobSource=\"proxy\",le!=\"+Inf\"}[$__rate_interval])\n  ) by (le)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blobstore",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 18, "x": 5, "y": 20 },
   "targets": [
    {
     "expr": "sum(\n    rate(devtool_registry_facade_registry_blob_req_bytes_second_bucket{cluster=~\"$cluster\", blobSource=\"blobstore\",le!=\"+Inf\"}[$__rate_interval])\n  ) by (le)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IPFS",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 18, "x": 5, "y": 30 },
   "targets": [
    {
     "expr": "sum(\n    rate(devtool_registry_facade_registry_blob_req_bytes_second_bucket{cluster=~\"$cluster\", blobSource=\"ipfs\",le!=\"+Inf\" }[$__rate_interval])  \n  ) by (le) \n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}